### ISSUE TITLE
Error running offline-analysis-example.py in examples/  during mobileinsight installation verification

### ISSUE THREAD

**Issue by jaideepcs-gh** [mobile-insight/mobileinsight-core#100]
### Versions

* OS: Mac OSX and Ubuntu (via mobileinsight-dev)
* Python version: 3.7.10 and 3.8.5
* Python installation method: 
* 

### Description

Running  offline-analysis-example.py results in an error.

This is also seen with other log files.

### Code and Logs

```python
python3 offline-analysis-example.py

```

```shell
Init RRC Analyzer
[INFO] [OfflineReplayer]: Enable LTE_RRC_OTA_Packet
[INFO] [OfflineReplayer]: Enable LTE_RRC_Serv_Cell_Info
[INFO] [OfflineReplayer]: Enable LTE_RRC_CDRX_Events_Info
[INFO] [WcdmaRrcAnalyzer]: Initialing WcdmaRrcAnalyzer..
[INFO] [OfflineReplayer]: Enable WCDMA_RRC_OTA_Packet
[INFO] [OfflineReplayer]: Enable WCDMA_RRC_Serv_Cell_Info
[INFO] [OfflineReplayer]: Enable WCDMA_RRC_States
[INFO] [OfflineReplayer]: Enable LTE_NAS_ESM_OTA_Incoming_Packet
[INFO] [OfflineReplayer]: Enable LTE_NAS_ESM_OTA_Outgoing_Packet
[INFO] [OfflineReplayer]: Enable LTE_NAS_EMM_OTA_Incoming_Packet
[INFO] [OfflineReplayer]: Enable LTE_NAS_EMM_OTA_Outgoing_Packet
[INFO] [OfflineReplayer]: Enable LTE_NAS_EMM_State
[INFO] [OfflineReplayer]: Enable LTE_NAS_ESM_State
[INFO] [UmtsNasAnalyzer]: Initialing UmtsNasAnalyzer..
[INFO] [OfflineReplayer]: Enable UMTS_NAS_OTA_Packet
[INFO] [OfflineReplayer]: Enable UMTS_NAS_GMM_State
[INFO] [OfflineReplayer]: Enable UMTS_NAS_MM_State
[INFO] [OfflineReplayer]: Enable UMTS_NAS_MM_REG_State
[INFO] [OfflineReplayer]: Enable LTE_PHY_PDSCH_Packet
[INFO] [OfflineReplayer]: Enable LTE_PHY_PUSCH_CSF
[INFO] [OfflineReplayer]: Enable LTE_MAC_UL_Tx_Statistics
[INFO] [OfflineReplayer]: Enable LTE_PHY_PUCCH_Tx_Report
[INFO] [OfflineReplayer]: Enable LTE_PHY_PUSCH_Tx_Report
[INFO] [OfflineReplayer]: Enable LTE_MAC_UL_Buffer_Status_Internal
[INFO] [OfflineReplayer]: Enable LTE_PHY_PDSCH_Stat_Indication
[INFO] [OfflineReplayer]: STARTED: 1619740498.4493096
[INFO] [OfflineReplayer]: Loading ./offline_log_example.mi2log
[INFO] [OfflineReplayer]: Loading: 1619740498.449642
[INFO] [UmtsNasAnalyzer]: Find One UMTS_NAS_MM_State
[INFO] [UmtsNasAnalyzer]: MmStatus MM.state=MM_IDLE MM.substate=MM_NO_CELL_AVAILABLE MM.update_status=UPDATED PLMN=unknown LAC=unknown RAC=unknown Network_operation_mode=unknown CS/PS_service_type=unknown
[INFO] [UmtsNasAnalyzer]: MM State: MM_IDLE
[INFO] [UmtsNasAnalyzer]: Find One UMTS_NAS_GMM_State
[INFO] [UmtsNasAnalyzer]: GMM State: GMM_DEREGISTERED
[INFO] [LteNasAnalyzer]: EmmStatus EMM.state=EMM_DEREGISTERED EMM.substate=EMM_DEREGISTERED_ATTACH_NEEDED MCC=310 MNC=410 MMEGI=0x50ff MMEC=0x16 TMSI=0x77fd95c0
[INFO] [LteNasAnalyzer]: Call flow status: IDLE
[INFO] [LteNasAnalyzer]: EMM state: EMM_DEREGISTERED
[INFO] [UmtsNasAnalyzer]: Find One UMTS_NAS_GMM_State
[INFO] [UmtsNasAnalyzer]: Find One UMTS_NAS_GMM_State
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/monitor/offline_replayer.py", line 209, in run
    self.send(event)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/element.py", line 104, in send
    self.to_list[i].recv(self, event)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/analyzer/analyzer.py", line 234, in recv
    self.source_callback[i](event)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/analyzer/lte_rrc_analyzer.py", line 249, in __rrc_filter
    self.__callback_sib_config(xml_msg)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/analyzer/lte_rrc_analyzer.py", line 407, in __callback_sib_config
    int(field_val['lte-rrc.utra_q_RxLevMin']) * 2,
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

**Comment by happyqiaomai** [comment]
Thanks for the post. Fixed.

**Comment by futuredimensions1** [comment]
Hi 

there is a similar error with ln 451 of lte_rrc_analyzer.py (see trace below). Could you please let me know how to fix this?
Thanks

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/monitor/offline_replayer.py", line 209, in run
    self.send(event)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/element.py", line 104, in send
    self.to_list[i].recv(self, event)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/analyzer/analyzer.py", line 234, in recv
    self.source_callback[i](event)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/analyzer/lte_rrc_analyzer.py", line 249, in __rrc_filter
    self.__callback_sib_config(xml_msg)
  File "/usr/local/lib/python3.8/dist-packages/MobileInsight-5.0.0-py3.8-linux-x86_64.egg/mobile_insight/analyzer/lte_rrc_analyzer.py", line 451, in __callback_sib_config
    int(field_val['lte-rrc.utra_q_RxLevMin']) * 2,
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Failed to run offline analysis example!
Exiting with status 4.
