### ISSUE TITLE
ImportError: No module named dm_collector_c

### ISSUE THREAD

**Issue by xsh6528** [mobile-insight/mobileinsight-core#24]
### Versions

* OS: macOS
* Python version: 2.7
* mobile-insight version: 3.2.0 release

### Description

I am importing an `MsgLogger` in interactive Python shell.

```python
>>> from mobile_insight.analyzer import MsgLogger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mobile_insight/__init__.py", line 9, in <module>
    import analyzer
  File "mobile_insight/analyzer/__init__.py", line 51, in <module>
    from log_analyzer import LogAnalyzer
  File "mobile_insight/analyzer/log_analyzer.py", line 15, in <module>
    from mobile_insight.monitor import OfflineReplayer
  File "mobile_insight/monitor/__init__.py", line 26, in <module>
    from dm_collector import *  # P4A: THIS LINE WILL BE DELETED ###
  File "mobile_insight/monitor/dm_collector/__init__.py", line 10, in <module>
    from dm_collector import DMCollector  # P4A: THIS LINE WILL BE DELETED ###
  File "mobile_insight/monitor/dm_collector/dm_collector.py", line 22, in <module>
    import dm_collector_c
ImportError: No module named dm_collector_c
```

It tried to import a `dm_collector_c` module and failed to find it.
Also, I can't understand why we can import `dm_collector_c`.

Because from my view, the directory `dm_collector_c` has only `.h` `.cpp` files.
No `__init.py` file exitsts.

Does this indicate I didn't install mobile-insight-core successfully.

**Comment by zwyuan** [comment]
`dm_collector_c` will be compile to `dm_collector_c.so`.
Can you check your installation log and also the python setup.py log?
Seems to me that it does not install successfully.
Also, on Mac, use `python2` installed by Homebrew instead of the system `python`, if you have not symlinked these two.
