### ISSUE TITLE
Core doesn't handle some message type & protocol version / PHY_x not working with MNO "Free" (France)

### ISSUE THREAD

**Issue by Gigithecode** [mobile-insight/mobileinsight-core#26]
[mi2log_20171117_140011.txt](https://github.com/mobile-insight/mobileinsight-core/files/1482409/mi2log_20171117_140011.txt)

[mi2log_20171117_140008.txt](https://github.com/mobile-insight/mobileinsight-core/files/1482408/mi2log_20171117_140008.txt)

[Demo-PHY-offline_log.txt](https://github.com/mobile-insight/mobileinsight-core/files/1482399/Demo-PHY-offline_log.txt)

[NetLogger_log.txt](https://github.com/mobile-insight/mobileinsight-core/files/1482401/NetLogger_log.txt)

[Demo-PHY-online_log.txt](https://github.com/mobile-insight/mobileinsight-core/files/1482400/Demo-PHY-online_log.txt)

### Versions

* OS: Android 4.4.2
* Python version: 2.7
* Python installation method: python-for-android
* 

### Description

When trying to run plugin DEMO_PHY_ONLINE or DEMO_PHY_OFFLINE (from a log recorded with NetLoger) with the French MNO "Free" I get errors because the plugin (or the core?) doesn't handle some message types or some protocol versions.
Importing the log to the desktop app. clairly show the problem.

### Code & shell

```
#!/usr/bin/python
# Filename: offline-analysis-filtering.py
import os
import sys

"""
Offline analysis: save the log as a new one with pre-defined filter
"""

#Import MobileInsight modules
from mobile_insight.monitor import OfflineReplayer

if __name__ == "__main__":
    
    # Initialize a 3G/4G monitor
    src = OfflineReplayer()
    src.set_input_path("./offline_log_example.mi2log")

    # Configure the log to be saved
    src.enable_log("LTE_PHY_PDSCH_Packet")

    # Save log as
    src.save_log_as("./filtered_log.mi2log")

    #Start the monitoring
    src.run()
```

```python
$ python offline-analysis-filtering.py
{}
[INFO] [OfflineReplayer]: Enable LTE_PHY_PDSCH_Packet
[INFO] [OfflineReplayer]: Loading ./offline_log_example.mi2log
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
...
-----------------------
$ python offline-analysis-example.py 
{}
[INFO] [OfflineReplayer]: Enable LTE_RRC_OTA_Packet
[INFO] [OfflineReplayer]: Enable LTE_RRC_Serv_Cell_Info
[WARNING] [OfflineReplayer]: Unsupported log message type: LTE_RRC_CDRX_Events_Info
[INFO] [OfflineReplayer]: Enable LTE_RRC_CDRX_Events_Info
Traceback (most recent call last):
  File "offline-analysis-example.py", line 28, in <module>
    lte_rrc_analyzer.set_source(src) #bind with the monitor
  File "/usr/local/lib/python2.7/dist-packages/mobile_insight/analyzer/lte_rrc_analyzer.py", line 847, in set_source
    source.enable_log("LTE_RRC_CDRX_Events_Info")
  File "/usr/local/lib/python2.7/dist-packages/mobile_insight/monitor/offline_replayer.py", line 126, in enable_log
    dm_collector_c.set_filtered(self._type_names)
ValueError: Wrong type name.
------------------------
openning the same log file with Mobileinsight-gui ;
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE LL1 PDSCH Demapper Configuration version: 0x1
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
Unknown LTE ML1 CMLIFMR version: 0x2
...
```

```

**Comment by zwyuan** [comment]
Thanks for the log report. It seems that MobileInsight currently cannot support the carrier config your phone has been using. Is it possible that you can enable the LTE_RRC_OTA message and see if it is enabled?

**Comment by Gigithecode** [comment]
It seems LTE_RRC_OTA succeed (see attached log)
But perhaps i miss something.

**Comment by Gigithecode** [comment]
![2017_11_23_00 31 18](https://user-images.githubusercontent.com/5233517/33167689-a40d326a-d03e-11e7-9cda-af6feef9178f.png)
[RrcAnalysis_log.txt](https://github.com/mobile-insight/mobileinsight-core/files/1498636/RrcAnalysis_log.txt)
