### ISSUE TITLE
ImportError: No module named dm_collector_c 

### ISSUE THREAD

**Issue by canerK** [mobile-insight/mobileinsight-core#49]
### Versions

* OS: Ubuntu 18.04
* Python version: Python 2.7.15rc1
* Python installation method: apt

### Description
When the latest version of mobileinsight-core is installed and run the python API - offline analysis url: > http://www.mobileinsight.net/tutorial-api.html#offline-analysis

**receiving an error as indicated below:**

### Code and Logs
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from mobile_insight.monitor import OfflineReplayer
  File "/home/ubuntu/mobileinsight-core/mobile_insight/__init__.py", line 9, in <module>
    import analyzer
  File "/home/ubuntu/mobileinsight-core/mobile_insight/analyzer/__init__.py", line 48, in <module>
    from log_analyzer import LogAnalyzer
  File "/home/ubuntu/mobileinsight-core/mobile_insight/analyzer/log_analyzer.py", line 15, in <module>
    from mobile_insight.monitor import OfflineReplayer
  File "/home/ubuntu/mobileinsight-core/mobile_insight/monitor/__init__.py", line 26, in <module>
    from dm_collector import *  # P4A: THIS LINE WILL BE DELETED ###
  File "/home/ubuntu/mobileinsight-core/mobile_insight/monitor/dm_collector/__init__.py", line 10, in <module>
    from dm_collector import DMCollector  # P4A: THIS LINE WILL BE DELETED ###
  File "/home/ubuntu/mobileinsight-core/mobile_insight/monitor/dm_collector/dm_collector.py", line 22, in <module>
    import dm_collector_c
ImportError: No module named dm_collector_c

```python

import os
import sys

from mobile_insight.monitor import OfflineReplayer
from mobile_insight.analyzer import LteRrcAnalyzer,WcdmaRrcAnalyzer


src = OfflineReplayer()
# Load offline logs
src.set_input_path("./offline_log_example.mi2log")

# RRC analyzer
lte_rrc_analyzer = LteRrcAnalyzer()
lte_rrc_analyzer.set_source(src) #bind with the monitor

wcdma_rrc_analyzer = WcdmaRrcAnalyzer()
wcdma_rrc_analyzer.set_source(src) #bind with the monitor

src.run()

```

**Comment by moonsky219** [comment]
It seems the dm_collector_c module is not properly compiled or installed. Please check the installation procedure.
