### ISSUE TITLE
Mac osx:

### ISSUE THREAD

**Issue by BeiluobluesNing** [mobile-insight/mobileinsight-core#60]
### Versions

* OS: 10.14.5
* Python version:2.7.16
* Python installation method:build in
* 

### Description
 
when execute all of python file in the examples, it will present the same prob"OSError: [Errno 2] No such file or directory"

### Code and Logs

```python
python offline-analysis-filtering.py
python monitor-example.py 8888 2000
and so on
```

```shell

Traceback (most recent call last):
  File "lte-measurement-example.py", line 23, in <module>
    src = OnlineMonitor()
  File "build/bdist.macosx-10.14-x86_64/egg/mobile_insight/monitor/online_monitor.py", line 156, in __init__
  File "build/bdist.macosx-10.14-x86_64/egg/mobile_insight/monitor/dm_collector/dm_collector.py", line 49, in __init__
  File "build/bdist.macosx-10.14-x86_64/egg/mobile_insight/monitor/dm_collector/dm_endec/dm_log_packet.py", line 439, in init
  File "build/bdist.macosx-10.14-x86_64/egg/mobile_insight/monitor/dm_collector/dm_endec/ws_dissector.py", line 104, in init_proc
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by yuanjieli** [comment]
This is caused by the unsuccessful installation of MobileInsight. Please re-run `install-mac.sh` or 'install-linux.sh`, or use the all-in-one VM image
