### ISSUE TITLE
Ubuntu1804 ImportError: No module named dm_collector_c

### ISSUE THREAD

**Issue by yuanyehome** [mobile-insight/mobileinsight-core#63]
### Versions

* OS: Ubuntu1804
* Python version: python2.7
* Python installation method: anaconda
* 

### Description

execute ./install-ubuntu.sh

### Code and Logs

While installing:
Installed /usr/local/lib/python2.7/dist-packages/MobileInsight-4.0.0-py2.7-linux-x86_64.egg
Processing dependencies for MobileInsight==4.0.0
Finished processing dependencies for MobileInsight==4.0.0
Installing GUI for MobileInsight...
Testing the MobileInsight offline analysis example.
Traceback (most recent call last):
  File "offline-analysis-example.py", line 11, in <module>
    from mobile_insight.monitor import OfflineReplayer
ImportError: No module named mobile_insight.monitor
Failed to run offline analysis example!
Exiting with status 4.

When using in my own pythonfile:
>>> import mobile_insight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mobile_insight/__init__.py", line 9, in <module>
    import analyzer
  File "mobile_insight/analyzer/__init__.py", line 48, in <module>
    from log_analyzer import LogAnalyzer
  File "mobile_insight/analyzer/log_analyzer.py", line 15, in <module>
    from mobile_insight.monitor import OfflineReplayer
  File "mobile_insight/monitor/__init__.py", line 26, in <module>
    from dm_collector import *  # P4A: THIS LINE WILL BE DELETED ###
  File "mobile_insight/monitor/dm_collector/__init__.py", line 10, in <module>
    from dm_collector import DMCollector  # P4A: THIS LINE WILL BE DELETED ###
  File "mobile_insight/monitor/dm_collector/dm_collector.py", line 22, in <module>
    import dm_collector_c
ImportError: No module named dm_collector_c

**Comment by xiongxiong1996** [comment]
I encountered the same problem. How did you solve it at that time
