### ISSUE TITLE
Decode SIB's & NAS messages.

### ISSUE THREAD

**Issue by r00tb3** [mobile-insight/mobileinsight-core#68]
### Versions

* OS: Ubuntu-18.04.1
* Python version: 2.7.15
* Python installation method: ubuntu repo

### Description

I'm trying to decode SIB and NAS messages over LTE live on my rooted smartphone.
When I start the monitor-example.py by providing the device port and baud rate it shows nothing so I tried to add more messages to be logged by adding `LTE_RRC_Serv_Cell_Info_Log_Packet` to `src.enable_log` but the code crashes stating `ValueError: Wrong type name.`

### Code and Logs

```python
                        Python modified code for monitor-example.py

#!/usr/bin/python
# Filename: monitor-example.py
import os
import sys

# Import MobileInsight modules
from mobile_insight.monitor import OnlineMonitor
from mobile_insight.analyzer import MsgLogger

if __name__ == "__main__":

    if len(sys.argv) < 3:
        print "Error: please specify physical port name and baudrate."
        print __file__, "SERIAL_PORT_NAME BAUNRATE"
        sys.exit(1)

    # Initialize a 3G/4G monitor
    src = OnlineMonitor()
    src.set_serial_port(sys.argv[1])  # the serial port to collect the traces
    src.set_baudrate(int(sys.argv[2]))  # the baudrate of the port

    # Save the monitoring results as an offline log
    src.save_log_as("./monitor-example.mi2log")

    # Enable 3G/4G messages to be monitored. Here we enable RRC (radio
    # resource control) monitoring
    src.enable_log("LTE_RRC_OTA_Packet")
    src.enable_log("LTE_RRC_Serv_Cell_Info_Log_Packet")
    src.enable_log("LTE_RRC_Serv_Cell_Info_Log_Packet")
    src.enable_log("LTE_NAS_ESM_Plain_OTA_Incoming_Message")
    src.enable_log("LTE_NAS_ESM_Plain_OTA_Outgoing_Message")
    src.enable_log("LTE_NAS_EMM_Plain_OTA_Incoming_Message")
    src.enable_log("LTE_NAS_EMM_Plain_OTA_Outgoing_Message")
    src.enable_log("LTE_NAS_EMM_State")
    src.enable_log("LTE_NAS_ESM_State")
    src.enable_log("LTE_PHY_PDSCH_Decoding_Result")
    
    # src.enable_log("WCDMA_RRC_OTA_Packet")
    # src.enable_log("WCDMA_RRC_Serv_Cell_Info")

    # Dump the messages to std I/O. Comment it if it is not needed.
    dumper = MsgLogger()
    dumper.set_source(src)
    dumper.set_decoding(MsgLogger.XML)  # decode the message as xml

    # Start the monitoring
    src.run()


```

```shell
                        Shell log from the terminal.

sudo python monitor-example.py /dev/ttyUSB0 115200
[INFO] [OnlineMonitor]: Enable collection: LTE_RRC_OTA_Packet
[WARNING] [OnlineMonitor]: Unsupported log message type: LTE_RRC_Serv_Cell_Info_Log_Packet
[INFO] [OnlineMonitor]: Enable collection: LTE_RRC_Serv_Cell_Info_Log_Packet
Traceback (most recent call last):
  File "monitor-example.py", line 28, in <module>
    src.enable_log("LTE_RRC_Serv_Cell_Info_Log_Packet")
  File "build/bdist.linux-x86_64/egg/mobile_insight/monitor/dm_collector/dm_collector.py", line 96, in enable_log
ValueError: Wrong type name.


```

What am I doing wrong?

How do I decode the NAS messages?

Regards.

**Comment by moonsky219** [comment]
Please try to enable more messages or turn on/off airplane mode to trigger NAS messages. If neither helps, it could be related the device not support such way. You can try the MobileInsight app directly to collect traces.

**Comment by r00tb3** [comment]
@moonsky219 Thanks for the response.

> Please try to enable more messages or turn on/off airplane mode to trigger NAS messages. 

I have tried that but nothing works, the thing is when I connect my smartphone to my laptop and put it on charging mode in developers option I'm able to see ttyUSB0 and after hitting the python script nothing happens.

When I switch to Mass Storage in dev options I'm not able to detect ttyUSB0 and the device's internal storage is mounted in this condition I'm unable to listen to ttyUSB0.

I've tried listening to DIAG messages using [QCSuper](https://github.com/P1sec/QCSuper/issues/29) it works like charm and I always get `superuser access granted` with QCSuper as it is able to listen to `/dev/diag` but could not accomplish some tasks it as I could not decode asn1 messages manually over the terminal, I had to rely on Wireshark for decoding the messages.

>If neither helps, it could be related to the device not support such way. You can try the MobileInsight app directly to collect traces.

I've tried the android app too but I'll have to reprogram the app for my needs...
